# Problema 2

### item c

In [86]:
library(Biodem)


In [63]:
Ct<-matrix(c(0.3,-0.1,0,0.2,0,0,0,0.6,-0.1,0,-0.1,-0.1,-0.9,0,0.2,0,0,0,-1,0,0,1,0,0,0,-1,0,0,1,0,0,0,-1,0,0,1), ncol = 6)
C=t(Ct)

In [64]:
C

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  0.3 -0.1  0.0 0.2   0.0  0.0
[2,]  0.0  0.6 -0.1 0.0  -0.1 -0.1
[3,] -0.9  0.0  0.2 0.0   0.0  0.0
[4,] -1.0  0.0  0.0 1.0   0.0  0.0
[5,]  0.0 -1.0  0.0 0.0   1.0  0.0
[6,]  0.0  0.0 -1.0 0.0   0.0  1.0

In [65]:
u=c(2,1,0,0,0,0)
u

[1] 2 1 0 0 0 0

In [66]:
mu=solve(C)%*%u
mu

[,1]   
[1,]  6.8750
[2,] 14.3750
[3,] 30.9375
[4,]  6.8750
[5,] 14.3750
[6,] 30.9375

In [67]:
solve(C)%*%C

[,1] [,2]         [,3]          [,4] [,5]          [,6]        
[1,] 1    4.163336e-17 -2.775558e-17 0    -4.163336e-17 2.775558e-17
[2,] 0    1.000000e+00 -5.551115e-17 0     0.000000e+00 5.551115e-17
[3,] 0    1.665335e-16  1.000000e+00 0    -1.665335e-16 0.000000e+00
[4,] 0    4.163336e-17 -2.775558e-17 1    -4.163336e-17 2.775558e-17
[5,] 0    0.000000e+00 -5.551115e-17 0     1.000000e+00 5.551115e-17
[6,] 0    1.665335e-16  0.000000e+00 0    -1.665335e-16 1.000000e+00

In [62]:
solve(C)

[,1]   [,2]   [,3]  [,4]   [,5]   [,6]  
[1,] -12.50  -2.50 -2.50  -2.50 -0.250 -0.250
[2,] -22.50  -2.50 -2.50  -4.50 -0.250 -0.250
[3,] -56.25 -11.25 -6.25 -11.25 -1.125 -1.125
[4,] -12.50  -2.50 -2.50  -1.50 -0.250 -0.250
[5,] -22.50  -2.50 -2.50  -4.50  0.750 -0.250
[6,] -56.25 -11.25 -6.25 -11.25 -1.125 -0.125

## item d

In [76]:
J<- matrix(c(1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0),nrow=3)
J

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    0    0    0    0   
[2,] 0    1    0    0    0    0   
[3,] 0    0    1    0    0    0

In [78]:
Jt=t(J)
Jt

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1   
[4,] 0    0    0   
[5,] 0    0    0   
[6,] 0    0    0

In [79]:
A<-diag(6)-C
A

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0.7  0.1  0.0  -0.2 0.0  0.0 
[2,] 0.0  0.4  0.1   0.0 0.1  0.1 
[3,] 0.9  0.0  0.8   0.0 0.0  0.0 
[4,] 1.0  0.0  0.0   0.0 0.0  0.0 
[5,] 0.0  1.0  0.0   0.0 0.0  0.0 
[6,] 0.0  0.0  1.0   0.0 0.0  0.0

In [81]:
phi_1=J%*%A%*%Jt
phi_1

[,1] [,2] [,3]
[1,] 0.7  0.1  0.0 
[2,] 0.0  0.4  0.1 
[3,] 0.9  0.0  0.8

In [88]:
phi_2=J%*%mtx.exp(A,2)%*%Jt
phi_2

[,1] [,2] [,3]
[1,] 0.29 0.11 0.01
[2,] 0.09 0.26 0.22
[3,] 1.35 0.09 0.64

In [91]:
phi_3=J%*%mtx.exp(A,3)%*%Jt
phi_3

[,1]  [,2]  [,3] 
[1,] 0.072 0.083 0.029
[2,] 0.261 0.153 0.242
[3,] 1.341 0.171 0.521

In [89]:
phi_4=J%*%mtx.exp(A,4)%*%Jt
phi_4

[,1]   [,2]   [,3]  
[1,] 0.0185 0.0514 0.0425
[2,] 0.3825 0.1133 0.2349
[3,] 1.1376 0.2115 0.4429

In [90]:
phi_5=J%*%mtx.exp(A,5)%*%Jt
phi_5

[,1]    [,2]    [,3]   
[1,] 0.03680 0.03071 0.04744
[2,] 0.42696 0.09887 0.21455
[3,] 0.92673 0.21546 0.39257