# Problema 2

### item b

In [1]:
library(Biodem) #Librería utilizada para elevar a una potencia una matriz usando el comando mtx.exp(MATRIZ,EXPONENTE)

In [2]:
Ct<-matrix(c(0.3,-0.1,0,0.2,0,0,0,0.6,-0.1,0,-0.1,-0.1,-0.9,0,0.2,0,0,0,-1,0,0,1,0,0,0,-1,0,0,1,0,0,0,-1,0,0,1), ncol = 6) #La matriz esta transpuesta
C=t(Ct) #MATRIZ I_{k}-Az

In [3]:
C

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  0.3 -0.1  0.0 0.2   0.0  0.0
[2,]  0.0  0.6 -0.1 0.0  -0.1 -0.1
[3,] -0.9  0.0  0.2 0.0   0.0  0.0
[4,] -1.0  0.0  0.0 1.0   0.0  0.0
[5,]  0.0 -1.0  0.0 0.0   1.0  0.0
[6,]  0.0  0.0 -1.0 0.0   0.0  1.0

In [4]:
solve(C) #inversa de la matriz MATRIZ I_{k}-Az

[,1]    [,2]   [,3]   [,4]    [,5]    [,6]   
[1,]  3.1250 0.6250 0.6250 -0.6250 0.06250 0.06250
[2,]  5.6250 3.1250 3.1250 -1.1250 0.31250 0.31250
[3,] 14.0625 2.8125 7.8125 -2.8125 0.28125 0.28125
[4,]  3.1250 0.6250 0.6250  0.3750 0.06250 0.06250
[5,]  5.6250 3.1250 3.1250 -1.1250 1.31250 0.31250
[6,] 14.0625 2.8125 7.8125 -2.8125 0.28125 1.28125

In [5]:
nu=c(2,1,0,0,0,0) #Vector de "desfase"
nu

[1] 2 1 0 0 0 0

In [6]:
mu=solve(C)%*%nu #Vector de medias sin multiplicar por el vector J
mu

[,1]   
[1,]  6.8750
[2,] 14.3750
[3,] 30.9375
[4,]  6.8750
[5,] 14.3750
[6,] 30.9375

In [7]:
J<- matrix(c(1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0),nrow=3) #Matriz J
J

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    0    0    0    0   
[2,] 0    1    0    0    0    0   
[3,] 0    0    1    0    0    0

In [8]:
J%*%mu #Vector de medias

[,1]   
[1,]  6.8750
[2,] 14.3750
[3,] 30.9375

## item d

In [9]:
J<- matrix(c(1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0),nrow=3) #Matriz J
J

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    0    0    0    0   
[2,] 0    1    0    0    0    0   
[3,] 0    0    1    0    0    0

In [10]:
Jt=t(J)
Jt #Transpuesta matriz J

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1   
[4,] 0    0    0   
[5,] 0    0    0   
[6,] 0    0    0

In [11]:
A<-diag(6)-C # Matriz A
A

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0.7  0.1  0.0  -0.2 0.0  0.0 
[2,] 0.0  0.4  0.1   0.0 0.1  0.1 
[3,] 0.9  0.0  0.8   0.0 0.0  0.0 
[4,] 1.0  0.0  0.0   0.0 0.0  0.0 
[5,] 0.0  1.0  0.0   0.0 0.0  0.0 
[6,] 0.0  0.0  1.0   0.0 0.0  0.0

## Parametros Phi's

In [12]:
phi_1=J%*%A%*%Jt 
phi_1

[,1] [,2] [,3]
[1,] 0.7  0.1  0.0 
[2,] 0.0  0.4  0.1 
[3,] 0.9  0.0  0.8

In [13]:
phi_2=J%*%mtx.exp(A,2)%*%Jt
phi_2

[,1] [,2] [,3]
[1,] 0.29 0.11 0.01
[2,] 0.09 0.26 0.22
[3,] 1.35 0.09 0.64

In [14]:
phi_3=J%*%mtx.exp(A,3)%*%Jt
phi_3

[,1]  [,2]  [,3] 
[1,] 0.072 0.083 0.029
[2,] 0.261 0.153 0.242
[3,] 1.341 0.171 0.521

In [15]:
phi_4=J%*%mtx.exp(A,4)%*%Jt
phi_4

[,1]   [,2]   [,3]  
[1,] 0.0185 0.0514 0.0425
[2,] 0.3825 0.1133 0.2349
[3,] 1.1376 0.2115 0.4429

In [16]:
phi_5=J%*%mtx.exp(A,5)%*%Jt
phi_5

[,1]    [,2]    [,3]   
[1,] 0.03680 0.03071 0.04744
[2,] 0.42696 0.09887 0.21455
[3,] 0.92673 0.21546 0.39257